import android.annotation.SuppressLint
import androidx.compose.runtime.Composable
import androidx.compose.runtime.rememberCoroutineScope
import androidx.compose.ui.platform.LocalContext
import database.ProjectFitnessContainer
import database.ProjectFitnessExercises
import kotlinx.coroutines.launch


@SuppressLint("CoroutineCreationDuringComposition")
@Composable
fun InsertProjectExercise(){

    val context = LocalContext.current
    val scopes = rememberCoroutineScope()
    var projectFitnessContainer = ProjectFitnessContainer(context)
    val itemRepo = projectFitnessContainer.itemsRepository
    scopes.launch {
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Barbell Bench Press" , bodyPart = "Chest" , secondaryMuscles = "Shoulder Triceps"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Cable Crossovers" , bodyPart = "Chest" , secondaryMuscles = "Shoulder"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Calf Raises" , bodyPart = "Calf" , secondaryMuscles = "None"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Chest Dip" , bodyPart = "Chest" , secondaryMuscles = "Abs Shoulder Triceps"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Chest Press" , bodyPart = "Chest" , secondaryMuscles = "Shoulder Triceps"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Close Grip Dumbbell Press" , bodyPart = "Chest" , secondaryMuscles = "Shoulder Triceps"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Decline Bench Press" , bodyPart = "Chest" , secondaryMuscles = "Shoulder Triceps"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Decline Dumbbell Bench Press" , bodyPart = "Chest" , secondaryMuscles = "Shoulder Triceps"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Dumbbell Bench Press" , bodyPart = "Chest" , secondaryMuscles = "Shoulder Triceps"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Dumbbell Flys" , bodyPart = "Chest" , secondaryMuscles = "Shoulder Triceps"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Dumbbell Pullover" , bodyPart = "Chest" , secondaryMuscles = "Lats Shoulder Triceps"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Hammer Strength Bench Press" , bodyPart = "Chest" , secondaryMuscles = "Shoulder Triceps"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Incline Barbell Bench Press" , bodyPart = "Chest" , secondaryMuscles = "Shoulder Triceps"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Incline Dumbbell Bench Press" , bodyPart = "Chest" , secondaryMuscles = "Shoulder Triceps"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Incline Dumbbell Flys" , bodyPart = "Chest" , secondaryMuscles = "Shoulder Triceps"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Leg Press" , bodyPart = "Quads" , secondaryMuscles = "Abs Adductors Calves Glutes Hamstrings Lower Back"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Pec Dec" , bodyPart = "Chest" , secondaryMuscles = "Shoulder"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Push Up" , bodyPart = "Chest" , secondaryMuscles = "Abs Shoulder Triceps"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Smith Machine Bench Press" , bodyPart = "Chest" , secondaryMuscles = "Shoulder Triceps"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Smith Machine Incline Bench Press" , bodyPart = "Chest" , secondaryMuscles = "Shoulder Triceps"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Standing Cable Fly" , bodyPart = "Chest" , secondaryMuscles = "Shoulder Triceps"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Squat" , bodyPart = "Quads" , secondaryMuscles = "Calves Glutes Hamstrings Lower Back"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Leg Extension" , bodyPart = "Quads" , secondaryMuscles = "None"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Machine Hack Squat" , bodyPart = "Quads" , secondaryMuscles = "Abs Adductors Calves Glutes Hamstrings Lower Back"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Dumbbell Squat" , bodyPart = "Quads" , secondaryMuscles = "Calves Glutes Hamstrings Lower Back"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Dumbbell Lunge" , bodyPart = "Quads" , secondaryMuscles = "Calves Glutes Hamstrings"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Front Squat" , bodyPart = "Quads" , secondaryMuscles = "Abs Adductors Calves Glutes Hamstrings Hip Flexors Upper Back"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Dumbbell Bulgarian Split Squat" , bodyPart = "Quads" , secondaryMuscles = "Abs Adductors Calves Glutes Hamstrings Shoulders Traps Upper Back"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Dumbbell Split Squat" , bodyPart = "Quads" , secondaryMuscles = "Abs Adductors Calves Glutes Hamstrings"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Plie Squat" , bodyPart = "Quads" , secondaryMuscles = "Abs Adductors Calves Glutes Hamstrings Lower Back"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Smith Machine Squat" , bodyPart = "Quads" , secondaryMuscles = "Abs Adductors Calves Glutes Hamstrings Lower Back"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Single Leg Extension" , bodyPart = "Quads" , secondaryMuscles = "None"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Box Jump" , bodyPart = "Quads" , secondaryMuscles = "Adductors Calves Glutes Hamstrings Hip Flexors"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Stiff Leg Deadlift" , bodyPart = "Hamstrings" , secondaryMuscles = "Abs Adductors Calves Glutes Lats Lower Back Quads Traps Upper Back"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Dumbbell Hamstrings Curl" , bodyPart = "Hamstrings" , secondaryMuscles = "None"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Trap Bar Deadlift" , bodyPart = "Hamstrings" , secondaryMuscles = "Abs Adductors Calves Forearms Glutes Lats Lower Back Quads Traps Upper Back"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Seated Leg Curl" , bodyPart = "Hamstrings" , secondaryMuscles = "Glutes"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Kettlebell Swing" , bodyPart = "Hamstrings" , secondaryMuscles = "Abs Adductors Calves Forearms Glutes Lats Lower Back Quads Traps Upper Back"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Sumo Deadlift" , bodyPart = "Hamstrings" , secondaryMuscles = "Abs Adductors Calves Forearms Glutes Lats Lower Back Quads Traps Upper Back"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Lying Leg Curl" , bodyPart = "Hamstrings" , secondaryMuscles = "None"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Nordic Hamstrings Curl" , bodyPart = "Hamstrings" , secondaryMuscles = "Abs Calves Glutes"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Seated Calf Raise" , bodyPart = "Calves" , secondaryMuscles = "None"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Leg Press Calf Raise" , bodyPart = "Calves" , secondaryMuscles = "None"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Standing Machine Calf Raise" , bodyPart = "Calves" , secondaryMuscles = "None"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Hyperextension" , bodyPart = "Glutes" , secondaryMuscles = "Hamstrings Lower Back"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Barbell Hip Thrust" , bodyPart = "Glutes" , secondaryMuscles = "Abs Hamstrings"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Standing Good Morning" , bodyPart = "Glutes" , secondaryMuscles = "Abs Hamstrings Lower Back Upper Back"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "IT Band Foam Rolling" , bodyPart = "IT Band" , secondaryMuscles = "None"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Plantar Fascia Lacrosse Ball" , bodyPart = "Plantar Fascia" , secondaryMuscles = "None"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Kneeling Posterior Hip Capsule Mobilization" , bodyPart = "Hip Flexors" , secondaryMuscles = "Glutes"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Hip Abduction Machine" , bodyPart = "Abductors" , secondaryMuscles = "Abs Glutes Hamstrings"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Straight Bar Triceps Extension" , bodyPart = "Triceps" , secondaryMuscles = "None"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Seated Dumbbell Tricep Extension" , bodyPart = "Triceps" , secondaryMuscles = "None"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Rope Triceps Extension" , bodyPart = "Triceps" , secondaryMuscles = "None"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Ez Bar Skullcrusher" , bodyPart = "Triceps" , secondaryMuscles = "None"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Lying Dumbbell Extension" , bodyPart = "Triceps" , secondaryMuscles = "Chest Shoulder"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Close Grip Bench Press" , bodyPart = "Triceps" , secondaryMuscles = "Chest Shoulder"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Tricep Dip" , bodyPart = "Triceps" , secondaryMuscles = "Chest Shoulder"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Dumbbell Floor Press" , bodyPart = "Triceps" , secondaryMuscles = "Chest Shoulder"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Lying Barbell Tricep Extension" , bodyPart = "Triceps" , secondaryMuscles = "None"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "French Press" , bodyPart = "Triceps" , secondaryMuscles = "None"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Bent Over Dumbbell Triceps Kickback" , bodyPart = "Triceps" , secondaryMuscles = "None"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Reverse Grip Cable Tricep Extension" , bodyPart = "Triceps" , secondaryMuscles = "None"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "One-Arm Standing Dumbbell Extension" , bodyPart = "Triceps" , secondaryMuscles = "None"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Weighted Tricep Dips" , bodyPart = "Triceps" , secondaryMuscles = "Chest Shoulder"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Two Arm Standing Dumbbell Extension" , bodyPart = "Triceps" , secondaryMuscles = "Abs"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Bench Dip" , bodyPart = "Triceps" , secondaryMuscles = "Shoulder"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Incline Skull Crusher" , bodyPart = "Triceps" , secondaryMuscles = "None"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Dumbbell Tricep Kickback" , bodyPart = "Triceps" , secondaryMuscles = "None"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Seated French Press" , bodyPart = "Triceps" , secondaryMuscles = "None"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "45 Degree Lying Tricep Extension" , bodyPart = "Triceps" , secondaryMuscles = "None"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Standing Low Pulley OverHead Tricep Extension" , bodyPart = "Triceps" , secondaryMuscles = "None"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "One-Arm Cable Tricep Extension" , bodyPart = "Triceps" , secondaryMuscles = "None"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Close Grip Push Up" , bodyPart = "Triceps" , secondaryMuscles = "Shoulder"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "High Pulley Overhead Tricep Extension" , bodyPart = "Triceps" , secondaryMuscles = "Abs"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Eccentric Only Dip" , bodyPart = "Triceps" , secondaryMuscles = "Abs Chest Shoulder"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "One-Arm Seated Dumbbell Extension" , bodyPart = "Triceps" , secondaryMuscles = "None"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Standing Dumbbell Curl" , bodyPart = "Biceps" , secondaryMuscles = "None"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Standing Hammer Curl" , bodyPart = "Biceps" , secondaryMuscles = "Forearms"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Incline Dumbbell Curl" , bodyPart = "Biceps" , secondaryMuscles = "Forearms"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Standing Barbell Curl" , bodyPart = "Biceps" , secondaryMuscles = "None"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Seated Barbell Wrist Curl" , bodyPart = "Forearms" , secondaryMuscles = "None"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Reverse Grip Barbell Curl" , bodyPart = "Forearms" , secondaryMuscles = "Bicep"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Behind-The-Back Barbell Wrist Curl" , bodyPart = "Forearms" , secondaryMuscles = "None"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Reverse Grip Barbell Wrist Curl" , bodyPart = "Forearms" , secondaryMuscles = "None"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "One-Arm Seated Dumbbell Wrist Curl" , bodyPart = "Forearms" , secondaryMuscles = "None"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Ez Bar Reverse Grip Barbell Curl" , bodyPart = "Forearms" , secondaryMuscles = "Bicep"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Reverse Dumbbell Wrist Curl Over Bench" , bodyPart = "Forearms" , secondaryMuscles = "None"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Lat Pulldown" , bodyPart = "Lats" , secondaryMuscles = "Abs Biceps Shoulders Upper Back"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Close Grip Lat Pulldown" , bodyPart = "Lats" , secondaryMuscles = "Abs Biceps Shoulders Upper Back"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Wide Grip Pull Up" , bodyPart = "Lats" , secondaryMuscles = "Abs Biceps Shoulders Upper Back"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Straight Arm Lat Pulldown" , bodyPart = "Lats" , secondaryMuscles = "Abs Biceps Shoulders Upper Back"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Chin Up" , bodyPart = "Lats" , secondaryMuscles = "Abs Biceps Shoulders Upper Back"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Reverse Grip Lat Pulldown" , bodyPart = "Lats" , secondaryMuscles = "Abs Biceps Shoulders Upper Back"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Wide Grip Lat Pulldown" , bodyPart = "Lats" , secondaryMuscles = "Abs Biceps Shoulders Upper Back"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Pull Up" , bodyPart = "Lats" , secondaryMuscles = "Abs Biceps Shoulders Upper Back"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Rope Straight Arm Pulldown" , bodyPart = "Lats" , secondaryMuscles = "Abs Biceps Shoulders Upper Back"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "V-Bar Pulldown" , bodyPart = "Lats" , secondaryMuscles = "Abs Biceps Shoulders Upper Back"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Shotgun Row" , bodyPart = "Lats" , secondaryMuscles = "Abs Biceps Shoulders Traps Upper Back"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "V-Bar Pull Up" , bodyPart = "Lats" , secondaryMuscles = "Biceps Middle Back Shoulders"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Weighted Pull Up" , bodyPart = "Lats" , secondaryMuscles = "Abs Biceps Shoulders Upper Back"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Weighted Chin Up" , bodyPart = "Lats" , secondaryMuscles = "Abs Biceps Shoulders Upper Back"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Close Grip Pull Up" , bodyPart = "Lats" , secondaryMuscles = "Abs Biceps Shoulders Upper Back"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Eccentric Only Pull Up" , bodyPart = "Lats" , secondaryMuscles = "Abs Biceps Shoulders Upper Back"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Underhand Close Grip Lateral Pulldown" , bodyPart = "Lats" , secondaryMuscles = "Biceps Middle Back"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Band Assisted Chin Up" , bodyPart = "Lats" , secondaryMuscles = "Abs Biceps Shoulders Upper Back"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Resistance Band Assisted Pull Up" , bodyPart = "Lats" , secondaryMuscles = "Abs Biceps Shoulders Upper Back"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Rack Lat Stretch" , bodyPart = "Lats" , secondaryMuscles = "None"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Resistance Band Assisted Pull Up" , bodyPart = "Lats" , secondaryMuscles = "Abs Biceps Shoulders Upper Back"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Behind Neck Lat Pulldown" , bodyPart = "Lats" , secondaryMuscles = "Abs Biceps Shoulders Upper Back"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Pull Up with Leg Raise" , bodyPart = "Lats" , secondaryMuscles = "Abs Biceps Shoulders Upper Back"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Close Grip Chin Up" , bodyPart = "Lats" , secondaryMuscles = "Abs Biceps Shoulders Upper Back"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Chin Up with Leg Raise" , bodyPart = "Lats" , secondaryMuscles = "Abs Biceps Shoulders Upper Back"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Rope Extension Lat Pulldown" , bodyPart = "Lats" , secondaryMuscles = "Biceps Middle Back Shoulders"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Standing Overhead Medicine Ball Throw" , bodyPart = "Lats" , secondaryMuscles = "Abs Triceps Upper Back"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Overhand Close Grip Lateral Pulldown" , bodyPart = "Lats" , secondaryMuscles = "Biceps Middle Back Shoulders"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Hip Abduction Machine" , bodyPart = "Abductors" , secondaryMuscles = "Abs Glutes Hamstrings"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Cable Hip Abduction" , bodyPart = "Abductors" , secondaryMuscles = "Glutes"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Lying Floor Leg Raise" , bodyPart = "Abs" , secondaryMuscles = "None"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Cable Crunch" , bodyPart = "Abs" , secondaryMuscles = "None"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Weighted Crunch" , bodyPart = "Abs" , secondaryMuscles = "None"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Dumbbell Side Bends" , bodyPart = "Abs" , secondaryMuscles = "None"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Plank" , bodyPart = "Abs" , secondaryMuscles = "Lower Back"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Hanging Leg Raise" , bodyPart = "Abs" , secondaryMuscles = "Forearms"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Ab Crunch" , bodyPart = "Abs" , secondaryMuscles = "None"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Side Plank" , bodyPart = "Abs" , secondaryMuscles = "Lower Back"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Decline Sit Up" , bodyPart = "Abs" , secondaryMuscles = "None"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Abdominal Air Bike" , bodyPart = "Abs" , secondaryMuscles = "None"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Abdominal Barbell Rollouts" , bodyPart = "Abs" , secondaryMuscles = "Shoulders"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Sit Up" , bodyPart = "Abs" , secondaryMuscles = "None"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Twisting Hanging Knee Raise" , bodyPart = "Abs" , secondaryMuscles = "Forearms"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Exercise Ball Crunch" , bodyPart = "Abs" , secondaryMuscles = "None"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Hip Adduction Machine" , bodyPart = "Adductors" , secondaryMuscles = "Glutes Hamstrings"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Alternating Lateral Lunge" , bodyPart = "Adductors" , secondaryMuscles = "Calves Hamstrings Shoulders Upper Back"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Deep Squat Prying" , bodyPart = "Adductors" , secondaryMuscles = "Glutes Hamstrings Hip Flexors Quads"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Adductor Foam Rolling" , bodyPart = "Adductors" , secondaryMuscles = "None"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Lateral Kneeling Adductor" , bodyPart = "Adductors" , secondaryMuscles = "Calves"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Rocking Frog Stretch" , bodyPart = "Adductors" , secondaryMuscles = "Shoulders Upper Back"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Seated Calf Raise" , bodyPart = "Calves" , secondaryMuscles = "None"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Seated Dumbbell Calf Raise" , bodyPart = "Calves" , secondaryMuscles = "None"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Bodyweight Standing Calf Raise" , bodyPart = "Calves" , secondaryMuscles = "None"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Standing One-Leg Calf Raise" , bodyPart = "Calves" , secondaryMuscles = "None"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "One-Leg Standing Bodyweight Calf Raise" , bodyPart = "Calves" , secondaryMuscles = "None"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "45 Degree Leg Press Calf Raise" , bodyPart = "Calves" , secondaryMuscles = "None"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Standing Machine Calf Raise" , bodyPart = "Calves" , secondaryMuscles = "None"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Standing Barbell Calf Raise" , bodyPart = "Calves" , secondaryMuscles = "None"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Smith Machine Calf Raise" , bodyPart = "Calves" , secondaryMuscles = "None"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Hack Squat Calf Raise" , bodyPart = "Calves" , secondaryMuscles = "None"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "One-Leg 45 Degree Calf Raise" , bodyPart = "Calves" , secondaryMuscles = "None"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Jump Rope" , bodyPart = "Calves" , secondaryMuscles = "Forearms"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Dumbbell Deadlift" , bodyPart = "Lower Back" , secondaryMuscles = "Calves Forearms Glutes Hamstrings Middle Back Quads Traps"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Superman" , bodyPart = "Lower Back" , secondaryMuscles = "Glutes"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Smith Machine Deadlift" , bodyPart = "Lower Back" , secondaryMuscles = "Calves Forearms Glutes Hamstrings Lats Middle Back Quads Traps"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "90/90 Hip Crossover" , bodyPart = "Lower Back" , secondaryMuscles = "Glutes Shoulders Upper Back"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Rollover Into V-Sits" , bodyPart = "Lower Back" , secondaryMuscles = "Adductors Hamstrings Upper Back"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "One Arm Dumbbell Row" , bodyPart = "Upper Back" , secondaryMuscles = "Abs Biceps Lats Shoulders"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Bent Over Row" , bodyPart = "Upper Back" , secondaryMuscles = "Abs Biceps Lats Lower Back Shoulders"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Bent Over Dumbbell Row" , bodyPart = "Upper Back" , secondaryMuscles = "Abs Biceps Lats Lower Back Shoulders"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Seated Cable Row" , bodyPart = "Upper Back" , secondaryMuscles = "Biceps Lats Shoulders"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Incline Bench Two Arm Dumbbell Row" , bodyPart = "Upper Back" , secondaryMuscles = "Biceps Lats Shoulders"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Neutral Grip Chest Supported Dumbbell Row" , bodyPart = "Upper Back" , secondaryMuscles = "Biceps Lats Shoulders"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Reverse Grip Bent-Over Dumbbell Row" , bodyPart = "Upper Back" , secondaryMuscles = "Biceps Lats Shoulders"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Feet Elevated Inverted Row" , bodyPart = "Upper Back" , secondaryMuscles = "Biceps Lats"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "T-Bar Row" , bodyPart = "Upper Back" , secondaryMuscles = "Abs Biceps Lats Lower Back Shoulders Traps"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Machine T-Bar Row" , bodyPart = "Upper Back" , secondaryMuscles = "Biceps Lats Shoulders"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Machine Row" , bodyPart = "Upper Back" , secondaryMuscles = "Biceps Lats"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Tripod Dumbbell Row" , bodyPart = "Upper Back" , secondaryMuscles = "Abs Biceps Lats Lower Back Shoulders"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Smith Machine Bent-Over Row" , bodyPart = "Upper Back" , secondaryMuscles = "Biceps Lats Shoulders"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Rope Crossover Seated Row" , bodyPart = "Upper Back" , secondaryMuscles = "Biceps Lats Shoulders"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "One-Arm Seated Cable Row" , bodyPart = "Upper Back" , secondaryMuscles = "Biceps Lats Triceps"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Rope Extension Incline Bench Cable Row" , bodyPart = "Upper Back" , secondaryMuscles = "Biceps Lats"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Reverse Grip Incline Bench Cable Row" , bodyPart = "Upper Back" , secondaryMuscles = "Biceps Lats"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Incline Bench Cable Row" , bodyPart = "Upper Back" , secondaryMuscles = "Biceps Lats"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Inverted Row" , bodyPart = "Upper Back" , secondaryMuscles = "Biceps Lats"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Neck Tiger Tail" , bodyPart = "Neck" , secondaryMuscles = "None"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Side Plank with Hip Dip" , bodyPart = "Obliques" , secondaryMuscles = "Abs"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Side Crunch" , bodyPart = "Obliques" , secondaryMuscles = "Abs"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Half Kneeling Cable Lift" , bodyPart = "Obliques" , secondaryMuscles = "Abs"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Split Stance Cable Chop" , bodyPart = "Obliques" , secondaryMuscles = "Abs"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Tall Kneeling Cable Chop" , bodyPart = "Obliques" , secondaryMuscles = "Abs"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Off Bench Oblique Hold" , bodyPart = "Obliques" , secondaryMuscles = "Abs"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Landmine Rotation" , bodyPart = "Obliques" , secondaryMuscles = "Abs"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Palmar Fascia Lacrosse Ball" , bodyPart = "Palmar Fascia" , secondaryMuscles = "None"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Plantar Fascia Lacrosse Ball" , bodyPart = "Plantar Fascia" , secondaryMuscles = "None"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Dumbbell Shrug" , bodyPart = "Traps" , secondaryMuscles = "Shoulders Upper Back"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Barbell Upright Row" , bodyPart = "Traps" , secondaryMuscles = "Biceps Shoulders"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Barbell Shrug" , bodyPart = "Traps" , secondaryMuscles = "Shoulders Upper Back"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Seated Dumbbell Shrug" , bodyPart = "Traps" , secondaryMuscles = "None"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Behind-The-Back Barbell Shrug" , bodyPart = "Traps" , secondaryMuscles = "None"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Machine Srug" , bodyPart = "Traps" , secondaryMuscles = "Shoulders Upper Back"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "High Pull" , bodyPart = "Traps" , secondaryMuscles = "Abs Adductors Biceps Calves Forearms Glutes Hamstrings Quads Shoulders Upper Back"))

        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Dumbbell Lateral Raise" , bodyPart = "Shoulders" , secondaryMuscles = "None"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Military Press" , bodyPart = "Shoulders" , secondaryMuscles = "Abs Traps Triceps"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Seated Dumbbell Press" , bodyPart = "Shoulders" , secondaryMuscles = "Traps Triceps"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Standing Dumbbell Shoulder Press" , bodyPart = "Shoulders" , secondaryMuscles = "Triceps"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Bent Over Dumbbell Reverse Fly" , bodyPart = "Shoulders" , secondaryMuscles = "Traps Triceps"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Smith Machine Shoulder Press" , bodyPart = "Shoulders" , secondaryMuscles = "Triceps"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Seated Arnold Press" , bodyPart = "Shoulders" , secondaryMuscles = "Traps Triceps"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Seated Bent Over Dumbbell Reverse Fly" , bodyPart = "Shoulders" , secondaryMuscles = "Traps Triceps"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Seated Barbell Shoulder Press" , bodyPart = "Shoulders" , secondaryMuscles = "Traps Triceps"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Seated Dumbbell Lateral Raise" , bodyPart = "Shoulders" , secondaryMuscles = "None"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Standing Cable Reverse Fly" , bodyPart = "Shoulders" , secondaryMuscles = "Traps Upper Back"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Cable Face Pull" , bodyPart = "Shoulders" , secondaryMuscles = "Traps Upper Back"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Machine Shoulder Press" , bodyPart = "Shoulders" , secondaryMuscles = "Traps Triceps"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Single Arm Cable Lateral Raise" , bodyPart = "Shoulders" , secondaryMuscles = "Traps"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Machine Reverse Fly" , bodyPart = "Shoulders" , secondaryMuscles = "Traps"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Cable Lateral Raise" , bodyPart = "Shoulders" , secondaryMuscles = "None"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Standing Dumbbell Front Raise" , bodyPart = "Shoulders" , secondaryMuscles = "None"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Seated Behind The Neck Shoulder Press" , bodyPart = "Shoulders" , secondaryMuscles = "Traps Triceps"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Barbell Front Raise" , bodyPart = "Shoulders" , secondaryMuscles = "Abs Traps"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Cable Upright Row" , bodyPart = "Shoulders" , secondaryMuscles = "Biceps Traps Upper Back"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Machine Latera Raise" , bodyPart = "Shoulders" , secondaryMuscles = "None"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Dumbbell Upright Row" , bodyPart = "Shoulders" , secondaryMuscles = "Biceps Traps Upper Back"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "One-Arm Dumbbell Lateral Raise" , bodyPart = "Shoulders" , secondaryMuscles = "None"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Smith Machine Upright Row" , bodyPart = "Shoulders" , secondaryMuscles = "Shoulders Traps"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Weight Plate Front Raise" , bodyPart = "Shoulders" , secondaryMuscles = "None"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Standing Arnold Press" , bodyPart = "Shoulders" , secondaryMuscles = "None"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Band Pull Apart" , bodyPart = "Shoulders" , secondaryMuscles = "Traps Upper Back"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Bent Over Low Pulley Rear Delt Fly" , bodyPart = "Shoulders" , secondaryMuscles = "Traps"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Incline Rear Delt Fly" , bodyPart = "Shoulders" , secondaryMuscles = "Traps Triceps"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Cable Front Raise" , bodyPart = "Shoulders" , secondaryMuscles = "Traps Upper Back"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Push Press" , bodyPart = "Shoulders" , secondaryMuscles = "Abs Traps Triceps"))
        itemRepo.insertProjectExercise(ProjectFitnessExercises(exerciseName = "Seated Neutral Grip Dumbbell Shoulder Press" , bodyPart = "Shoulders" , secondaryMuscles = "Traps Triceps"))
    }
}